{
	"layers": [
		{
			"name": "accent",
			"path": {
				"Mod": "windowelements/itemization/mirage_plate2_accent.tex"
			},
			"modifiers": [
				{
					"Color": {
						"value": {
							"Option": "Accent"
						}
					}
				}
			],
			"blend": "Normal"
		},
		{
			"name": "base",
			"path": {
				"Mod": "windowelements/itemization/mirage_plate2_base.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		}
	]
}