{
	"layers": [
		{
			"name": "underlay",
			"path": {
				"Mod": "ui/uld/partylist_bg_hr1.tex/Party and Alliance Background/Transparent/underlay.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		},
		{
			"name": "overlay_accent",
			"path": {
				"Mod": "ui/uld/partylist_bg_hr1.tex/Party and Alliance Background/Transparent/overlay_accent.tex"
			},
			"modifiers": [
				{
					"Color": {
						"value": {
							"Option": "Accent"
						}
					}
				}
			],
			"blend": "Normal"
		}
	]
}