{
	"layers": [
		{
			"name": "overlay_accent",
			"path": {
				"Mod": "windows/active/border/harpoon_h_accent.tex"
			},
			"modifiers": [
				{
					"Color": {
						"value": {
							"Option": "Accent"
						}
					}
				}
			],
			"blend": "Normal"
		},
		{
			"name": "base",
			"path": {
				"Mod": "windows/active/border/harpoon_h_base.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		}
	]
}