{
	"layers": [
		{
			"name": "contrast_hard2",
			"path": {
				"Mod": "combat/partylist_gaugehp/hard.tex"
			},
			"modifiers": [],
			"blend": "Overlay"
		},
		{
			"name": "contrast_hard",
			"path": {
				"Mod": "combat/partylist_gaugehp/hard.tex"
			},
			"modifiers": [],
			"blend": "Overlay"
		},
		{
			"name": "overlay_shield",
			"path": {
				"Mod": "combat/partylist_gaugehp/overlay_shield.tex"
			},
			"modifiers": [
				{
					"Color": {
						"value": {
							"Option": "Party List Shield Color"
						}
					}
				}
			],
			"blend": "Normal"
		},
		{
			"name": "underlay",
			"path": {
				"Mod": "combat/partylist_gaugehp/underlay.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		}
		
	]
}