{
	"layers": [
		{
			"name": "underlay",
			"path": {
				"Mod": "ui/uld/harpoonwindowa_selected_h_hr1.tex/Selected Window/Bar/underlay.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		},
		{
			"name": "overlay_accent",
			"path": {
				"Mod": "ui/uld/harpoonwindowa_selected_h_hr1.tex/Selected Window/Bar/overlay_accent.tex"
			},
			"modifiers": [
				{
					"Color": {
						"value": {
							"Option": "Accent"
						}
					}
				}
			],
			"blend": "Normal"
		}
	]
}