{
	"layers": [
		
		{
			"name": "glow_screen",
			"path": {
				"Mod": "icons/classjob_party/glow/icons/43_bst_screen.tex"
			},
			"modifiers": [],
			"blend": "Screen"
		},
		{
			"name": "glow_hardlight",
			"path": {
				"Mod": "icons/classjob_party/glow/icons/43_bst_hardlight.tex"
			},
			"modifiers": [],
			"blend": "HardLight"
		},
		{
			"name": "glow_color",
			"path": {
				"Mod": "icons/classjob_party/glow/icons/43_bst_color.tex"
			},
			"modifiers": [{
				"Color": {
					"value": {
						"Option": "Class/Job Color - Limited"
			}}}],
			"blend": "Normal"
		},
		{
			"name": "glow_shadow",
			"path": {
				"Mod": "icons/classjob_party/glow/icons/43_bst_shadow.tex"
			},
			"modifiers": [],
			"blend": "Normal"
		}
	]
}